// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"
import { eagerLoadControllersFrom } from "@hotwired/stimulus-loading"

// Eagerly load all Stimulus controllers under the controllers directory
eagerLoadControllersFrom("controllers", application)


import HelloController from "./hello_controller"
application.register("hello", HelloController)
